source "https://rubygems.org"

gem "sinatra"
gem "rack-flash3"
gem "rerun"
gem "activerecord"
gem "rspec"
gem "capybara"
gem "rake"
gem "pg", "~> 0.17.1"
gem "launchy"
gem "sinatra-contrib"
gem "gschool_database_connection", "~> 1.0.0"
gem "capistrano", "~> 3.2.0"
gem "json", "~> 1.8.1"